name: build-and-boot
jobs:
- armv5:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: armv5
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- armv7:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: armv7
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- arm64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: arm64
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- i386:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: i386
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- mips64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: mips64
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- mips64el:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: mips64el
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- ppc64le:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: ppc64le
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- riscv64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: riscv64
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- sparc64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: sparc64
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
- x86_64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT }}
    env:
      GIT_DEPTH: 1
      PYTHONUNBUFFERED: 1
      PLAN_URL: https://raw.githubusercontent.com/alok0366/actions-test/main/share/plans/plan.yml
      JOB_NAME: x86_64
    steps:
    - uses: actions/checkout@v4
    - run: 'export CCACHE_DIR=$PWD/ccache

        export SKIP_OVERLAYFS=true && tuxsuite plan execute $PLAN_URL -d $PWD --job-name
        $JOB_NAME --wrapper ccache --runtime podman'
