name: Docker Build and Publish Image

# on:
#   push:
#     tags:
#       - '*'
#     paths:
#       - 'Dockerfile'
#       - '*.py'

on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish Docker image
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/${{ github.repository_owner }}/tuxsuite:latest
          docker push ghcr.io/${{ github.repository_owner }}/tuxsuite:latest

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: actions/create-release@v1
        if: ${{ github.base_ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/') }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release ${{ github.ref }}"

