name: CI Workflow

on:
  workflow_dispatch:
  workflow_call:


jobs:
  generate-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/tuxsuite:latest

    env:
      PLAN: ${{ vars.TUXSUITE_PLAN_URL }}

    outputs:
      plan_jobs: ${{ steps.plan_jobs.outputs.jobs_list }}
      plan_url: ${{ steps.plan_url.outputs.PLAN }}

    steps:
      - uses: actions/checkout@v4

      - id: plan_url
        run: |
          if [ -z "${{ env.PLAN }}" ]; then
            PLAN="https://github.com/${{ github.repository_owner }}/actions-test/raw/main/share/plans/plan.yml"
            echo "PLAN=$PLAN" >> "$GITHUB_OUTPUT"
            echo "PLAN=$PLAN" >> $GITHUB_ENV
          fi
      - id: plan_jobs
        run: |
          generate_pipeline --plan "$PLAN"
          jobs_list=$(jq -c -r '.jobs' child_jobs.json)
          echo "jobs_list=$jobs_list" >> "$GITHUB_OUTPUT"



  tuxsuite-child-pipeline:
    needs: generate-pipeline
    strategy:
      fail-fast: false
      matrix:
        JOB_NAME: ${{ fromJson(needs.generate-pipeline.outputs.plan_jobs) }}

    uses: ./.github/workflows/tuxsuite_local.yml
    with:
      JOB_NAME: ${{ matrix.JOB_NAME }}
      PLAN_URL: ${{ needs.generate-pipeline.outputs.plan_url }}
